made project key non-optional

diff --git a/assets/out b/assets/out
--- a/assets/out
+++ b/assets/out
@@ -80,7 +80,10 @@ else
 fi
 
 sonar_project_key=$(jq -r '.params.project_key // ""' < "${payload}")
-if [ ! -z "${sonar_project_key}" ]; then
+if [ -z "${sonar_project_key}" ]; then
+  echo "error: params.project_key has not been specified."
+  exit 1
+else
   scanner_opts+=" -Dsonar.projectKey=\"${sonar_project_key}\""
 fi
 
